# General
set -g mouse on

# Windows and panes
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Open panes in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Popups
bind P display-popup -E -d "#{pane_current_path}" -w 80% -h 80% -T "Terminal"

# Theme
#set -g @tmux-gruvbox 'dark'
set -g status-position top


# Theme configuration
set -g status-position top

set -g @gruvbox-tmux_theme "medium"       # hard | medium | soft
set -g @gruvbox-tmux_transparent 0
set -g @gruvbox-tmux_time_format "24H"

# Window and pane numbering
set -g @gruvbox-tmux_window_id_style hsquare
set -g @gruvbox-tmux_pane_id_style super
set -g @gruvbox-tmux_zoom_id_style dsquare

# Battery
set -g @gruvbox-tmux_show_battery_widget 1
set -g @gruvbox-tmux_battery_name "BAT0"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'https://gitlab.com/motaz-shokry/gruvbox-tmux'

# TPM must remain last
run '~/.tmux/plugins/tpm/tpm'
# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @plugin 'egel/tmux-gruvbox'

# Initialize TPM, keep this at the bottom
run '~/.tmux/plugins/tpm/tpm'
